name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: lawnotation-ui
          build: npm run build
          start: npm preview, npx supabase start
          wait-on: 'http://localhost:3000, http://localhost:54323'
          wait-on-timeout: 120
